config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index' => 'welcome#index'
  root 'welcome#index'

  resources :professors
  resources :alunos
  resources :disciplinas

  get 'login'   => 'sessions#new'
  post 'access'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  validates :nome, presence: true
  validates :cpf, presence: true, length: { minimum: 11 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
  validates :nome, presence: true
  validates :ementa, presence: true, length: { maximum: 200 }
end

app/models/professor.rb
class Professor < ApplicationRecord
  validates :nome, presence: true
  validates :cpf, presence: true, length: { minimum: 11 }
end

app/models/sessao.rb
class Sessao
  attr_reader :ativa, :id, :senha
  private :ativa, :id, :senha

  def initialize()
    @id = "admin"
    @senha = "admin"
    @ativa = false
  end

  def logar(id, senha)
    if @id.eql?id and @senha.eql?senha
      @ativa = true
    else
      raise 'Usuario ou senha invalida'
    end
  end

  def logout
    @ativa = false
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  validates :name, presence: true, length: { minimum: 5, maximum: 255 }
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_digest, presence: true, length: { maximum: 255 }
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  include SessionsHelper
  before_action :logged_in_user

  def index
    @alunos = Aluno.all
  end

  def show
    @aluno = Aluno.find(params[:id])
  end

  def new
    @aluno = Aluno.new
  end

  def edit
    @aluno = Aluno.find(params[:id])
  end

  def create

    @aluno = Aluno.new(aluno_params)

    #model herda a funcao save
    if @aluno.save
      #redireciona para o model em questao
      redirect_to @aluno
    else
      render 'new'
    end
  end

  def update
    @aluno = Aluno.find(params[:id])
    if @aluno.update(aluno_params)
      redirect_to @aluno
    else
      render 'edit'
    end
  end

  def destroy
    @aluno = Aluno.find(params[:id])
    @aluno.destroy

    redirect_to alunos_path
  end

  private

  def aluno_params
    params.require(:aluno).permit(:nome, :cpf, :idade)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  include SessionsHelper
  before_action :logged_in_user

  def index
    @disciplinas = Disciplina.all
  end

  def show
    @disciplina = Disciplina.find(params[:id])
  end

  def new
    @disciplina = Disciplina.new
  end

  def edit
    @disciplina = Disciplina.find(params[:id])
  end

  def create

    @disciplina = Disciplina.new(disciplina_params)

    #model herda a funcao save
    if @disciplina.save
      #redireciona para o model em questao
      redirect_to @disciplina
    else
      render 'new'
    end
  end

  def update
    @disciplina = Disciplina.find(params[:id])
    if @disciplina.update(disciplina_params)
      redirect_to @disciplina
    else
      render 'edit'
    end
  end

  def destroy
    @disciplina = Disciplina.find(params[:id])
    @disciplina.destroy

    redirect_to disciplinas_path
  end

  private

  def disciplina_params
    params.require(:disciplina).permit(:nome, :ementa, :horas)
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  include SessionsHelper
  before_action :logged_in_user

  def index
    @professors= Professor.all
  end

  def show
    @professor = Professor.find(params[:id])
  end

  def new
    @professor = Professor.new
  end

  def edit
    @professor = Professor.find(params[:id])
  end

  def create
    #funcao recebe parametros tratados do professor cria um model professor
    @professor = Professor.new(professor_params)

    #model herda a funcao save
    if @professor.save
      #redireciona para o model em questao
      redirect_to @professor
    else
      render 'new'
    end
  end

  def update
    @professor = Professor.find(params[:id])
    if @professor.update(professor_params)
      redirect_to @professor
    else
      render 'edit'
    end
  end

  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    redirect_to professors_path
  end

  private
  #parametros para criar model professor, form :professor(nome, cpf, formacao)
  def professor_params
    params.require(:professor).permit(:nome, :cpf, :formacao)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  skip_before_action :verify_authenticity_token

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to :controller => 'welcome', :action => 'index'
    else
      flash[:danger] = 'Combinação de e-mail/senha incorreta'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to :controller => 'sessions', :action => 'new'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include SessionsHelper
  before_action :logged_in_user
  def index

  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Confirms a logged-in user or redirect
  def logged_in_user
    if !logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alunos/edit.html.erb
<h1>Editar - Aluno</h1>

<%= form_with scope: :aluno, url: alunos_path, local: true do |form| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@aluno.errors.count, "error") %> prohibited
        this alunor from being saved:
      </h2>
      <ul>
        <% @aluno.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </p>

  <p>
    <%= form.label :idade %><br>
    <%= form.text_field :idade %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Alunos</h1>

<%= link_to 'Cadastrar aluno', new_aluno_path %>

<br>
<br>
<br>

<table>
  <tr>
    <th>Nome</th>
    <th>Idade</th>
    <th></th>
  </tr>

 <% @alunos.each do |aluno| %>
    <tr>
      <td><%= aluno.nome %></td>
      <td><%= aluno.idade %></td>
      <td><%= link_to 'Mostrar', aluno_path(aluno) %></td>
      <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
      <td><%= link_to 'Destruir', aluno_path(aluno),
                      method: :delete,
                      data: { confirm: 'Você esta seguro disto?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<br>

<%= link_to 'Back', root_url %>

app/views/alunos/new.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Cadastro - Aluno</h1>

<%= form_with scope: :aluno, url: alunos_path, local: true do |form| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@aluno.errors.count, "error") %> prohibited
        this aluno from being saved:
      </h2>
      <ul>
        <% @aluno.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </p>

  <p>
    <%= form.label :idade %><br>
    <%= form.text_field :idade %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p>
  <strong>Nome Completo:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @aluno.idade %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/disciplinas/edit.html.erb
<h1>Editar - Disciplina</h1>

<%= form_with scope: :disciplina, url: disciplinas_path, local: true do |form| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@disciplina.errors.count, "error") %> prohibited
        this disciplina from being saved:
      </h2>
      <ul>
        <% @disciplina.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :ementa %><br>
    <%= form.text_area :ementa %>
  </p>

  <p>
    <%= form.label :horas %><br>
    <%= form.text_field :horas %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Disciplinas</h1>

<%= link_to 'Cadastrar disciplina', new_disciplina_path %>

<br>
<br>
<br>

<table>
  <tr>
    <th>Nome</th>
    <th>Horas</th>
    <th></th>
  </tr>

 <% @disciplinas.each do |disciplina| %>
    <tr>
      <td><%= disciplina.nome %></td>
      <td><%= disciplina.horas %></td>
      <td><%= link_to 'Mostrar', disciplina_path(disciplina) %></td>
      <td><%= link_to 'Editar', edit_disciplina_path(disciplina) %></td>
      <td><%= link_to 'Destruir', disciplina_path(disciplina),
                      method: :delete,
                      data: { confirm: 'Você esta seguro disto?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<br>

<%= link_to 'Back', root_url %>

app/views/disciplinas/new.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Cadastro - Disciplina</h1>

<%= form_with scope: :disciplina, url: disciplinas_path, local: true do |form| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@disciplina.errors.count, "error") %> prohibited
        this disciplina from being saved:
      </h2>
      <ul>
        <% @disciplina.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :ementa %><br>
    <%= form.text_area :ementa %>
  </p>

  <p>
    <%= form.label :horas %><br>
    <%= form.text_field :horas %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Ementa:</strong>
  <%= @disciplina.ementa %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @disciplina.horas %>
</p>

<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestaoacademica</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professors/edit.html.erb
<h1>Editar - Professor</h1>

<%= form_with scope: :professor, url: professors_path, local: true do |form| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@professor.errors.count, "error") %> prohibited
        this professor from being saved:
      </h2>
      <ul>
        <% @professor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </p>

  <p>
    <%= form.label :formacao %><br>
    <%= form.text_field :formacao %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Professores</h1>

<%= link_to 'Cadastrar professor', new_professor_path %>

<br>
<br>
<br>

<table>
  <tr>
    <th>Nome</th>
    <th>Formação</th>
    <th></th>
  </tr>

 <% @professors.each do |professor| %>
    <tr>
      <td><%= professor.nome %></td>
      <td><%= professor.formacao %></td>
      <td><%= link_to 'Mostrar', professor_path(professor) %></td>
      <td><%= link_to 'Editar', edit_professor_path(professor) %></td>
      <td><%= link_to 'Destruir', professor_path(professor),
                      method: :delete,
                      data: { confirm: 'Você esta seguro disto?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<br>

<%= link_to 'Back', root_url %>

app/views/professors/new.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h1>Cadastro - Professor</h1>

<%= form_with scope: :professor, url: professors_path, local: true do |form| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@professor.errors.count, "error") %> prohibited
        this professor from being saved:
      </h2>
      <ul>
        <% @professor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nome_completo %><br>
    <%= form.text_field :nome %>
  </p>

  <p>
    <%= form.label :cpf %><br>
    <%= form.text_field :cpf %>
  </p>

  <p>
    <%= form.label :formacao %><br>
    <%= form.text_field :formacao %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p>
  <strong>Nome Completo:</strong>
  <%= @professor.nome %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @professor.cpf %>
</p>

<p>
  <strong>Formacao:</strong>
  <%= @professor.formacao %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>

app/views/welcome/index.html.erb
<p align="right"><%= link_to 'Logout', logout_url %></p>
<h2 align="center">Gestão Academica</h2>

<p>
  <%= link_to 'Professores', controller: 'professors' %>
</p>
<p>
  <%= link_to 'Alunos', controller: 'alunos' %>
</p>
<p>
  <%= link_to 'Disciplinas', controller: 'disciplinas' %>
</p>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p align="center" >The time is now: <%= Time.now %></p>